[package]
name = "jwks-client"
version = "0.1.6"
authors = ["Jean-François Bilodeau <jfbilodeau@chronogears.com>"]
edition = "2018"
keywords = [ "jwt", "jwks", "jwk", "gcp" ]
categories = [ "web-programming", "cryptography", "authentication" ]
license = "MIT"
homepage = "https://github.com/jfbilodeau/jwks-client"
repository = "https://github.com/jfbilodeau/jwks-client"
description = "Library to validate JWT tokens using JSON Web Key Set (JWKS)"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rustls = ["reqwest/rustls-tls"]


[dependencies]
<<<<<<< HEAD
base64 = "^0.10.0"
reqwest = {version = "^0.9.0", default-features = false, features = ["json"]}
serde = "1"
serde_derive = "1"
serde_json = "1"
regex = "1"
ring = "^0.16.0"
